### ISSUE TITLE
Unable to run the project

### ISSUE THREAD

**Issue by mady143** [Pial-Diu/AutomaticQuestionGenerator#1]
Hi @Pial-Diu ,
                      I clone your project to my htdocs folder and started the xampp server the mysql server and apache2 server is running sucessfully but in the browser while open the localhost its showing me only apache2 default page but how can i run your project i was unable to understand
could you please help me in resolving this issue...

Thanks and Regards,
Manikantha Sekhar..

**Comment by Pial-Diu** [comment]
> Hi @Pial-Diu ,
> I clone your project to my htdocs folder and started the xampp server the mysql server and apache2 server is running sucessfully but in the browser while open the localhost its showing me only apache2 default page but how can i run your project i was unable to understand
> could you please help me in resolving this issue...
> 
> Thanks and Regards,
> Manikantha Sekhar..
